// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDa3G1qUgOEeVZ7nvDxvFnLmCc9F2PwA8',
    appId: '1:1096551649458:android:9154726894366e802df9ab',
    messagingSenderId: '1096551649458',
    projectId: 'ftc-tracker',
    databaseURL: 'https://ftc-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ftc-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL38u9CsHpVegIaV4wisBz2PJTghpkGcA',
    appId: '1:1096551649458:ios:8f635e1074ff93f12df9ab',
    messagingSenderId: '1096551649458',
    projectId: 'ftc-tracker',
    databaseURL: 'https://ftc-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ftc-tracker.appspot.com',
    iosClientId: '1096551649458-1pbo26jlp0rk8gso9dtkfvetaa1sj2a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftcTracker',
  );
}
